#### Task
Given the open-source datasets such as Daily Financial News for 6000+ Stocks and Huge Stock Market Dataset, the task aims to understand how news headlines affect the up and down trends of the stock market from 2014 to 2015. Then, an API will be built for the user to obtain the trend analysis of a selected stock after he/she enters a news headline.

In [ ]:
%pip install numpy
%pip install pandas

In [116]:
import numpy as np
import pandas as pd
import datetime

##### Prepare news headlines data in Daily Financial News for 6000+ Stocks Dataset
1. Loại bỏ các dữ liệu thiếu dữ kiện (Null, Nan) 
2. Lấy dữ liệu từ năm 2014 đến hết 2015
3. Lọc các mã có số lượng news headlines thấp

In [117]:
df = pd.read_csv('Datasets/analyst_ratings_processed.csv',index_col = 0)
df.head()

,title,date,stock
0.0,Stocks That Hit 52-Week Highs On Friday,2020-06-05 10:30:00-04:00,A
1.0,Stocks That Hit 52-Week Highs On Wednesday,2020-06-03 10:45:00-04:00,A
2.0,71 Biggest Movers From Friday,2020-05-26 04:30:00-04:00,A
3.0,46 Stocks Moving In Friday's Mid-Day Session,2020-05-22 12:45:00-04:00,A
4.0,B of A Securities Maintains Neutral on Agilent...,2020-05-22 11:38:00-04:00,A

In [118]:
df.isnull().sum()

title       0
date     1289
stock    2578
dtype: int64

In [119]:
df.describe()

                          title                       date    stock
count                   1400469                    1399180  1397891
unique                   843225                     648859     6192
top     Benzinga's Top Upgrades  2020-03-12 12:10:00-04:00      MRK
freq                       5349                       1703     3334

In [120]:
pre_df = df[df['date'].notna()]
pre_df.isnull().sum()

title       0
date        0
stock    1289
dtype: int64

In [122]:
pre_df = df[df['stock'].notna()]
pre_df.isnull().sum()

title    0
date     0
stock    0
dtype: int64

In [123]:
pre_df['year'] = [int(str(d).split(' ')[0].split('-')[0]) for d in pre_df['date']]
pre_df.head()

C:\Users\DELL\AppData\Local\Temp\ipykernel_13436\1585511652.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pre_df['year'] = [int(str(d).split(' ')[0].split('-')[0]) for d in pre_df['date']]

,title,date,stock,year
0.0,Stocks That Hit 52-Week Highs On Friday,2020-06-05 10:30:00-04:00,A,2020
1.0,Stocks That Hit 52-Week Highs On Wednesday,2020-06-03 10:45:00-04:00,A,2020
2.0,71 Biggest Movers From Friday,2020-05-26 04:30:00-04:00,A,2020
3.0,46 Stocks Moving In Friday's Mid-Day Session,2020-05-22 12:45:00-04:00,A,2020
4.0,B of A Securities Maintains Neutral on Agilent...,2020-05-22 11:38:00-04:00,A,2020

In [124]:
# Lọc news headlines trong thời gian từ 2014 đến 2015
pre_df = pre_df[pre_df.year >= 2014]
pre_df

,title,date,stock,year
0.0,Stocks That Hit 52-Week Highs On Friday,2020-06-05 10:30:00-04:00,A,2020
1.0,Stocks That Hit 52-Week Highs On Wednesday,2020-06-03 10:45:00-04:00,A,2020
2.0,71 Biggest Movers From Friday,2020-05-26 04:30:00-04:00,A,2020
3.0,46 Stocks Moving In Friday's Mid-Day Session,2020-05-22 12:45:00-04:00,A,2020
4.0,B of A Securities Maintains Neutral on Agilent...,2020-05-22 11:38:00-04:00,A,2020
...,...,...,...,...
1413824.0,5 Consumer Goods Stocks With The Lowest PEG Ratio,2014-09-02 09:30:00-04:00,ZX,2014
1413825.0,China Zenix Auto International Limited Reports...,2014-08-21 07:23:00-04:00,ZX,2014
1413826.0,China Zenix Auto Reports Q1 EPS of $0.04; Reve...,2014-05-15 05:41:00-04:00,ZX,2014
1413827.0,China Zenix Names Martin Cheung as CFO,2014-03-06 06:19:00-05:00,ZX,2014
1413828.0,China Zenix CFO Yifan Li Resigns for Personal ...,2014-02-24 06:37:00-05:00,ZX,2014

In [125]:
# Lọc news headlines trong thời gian từ 2014 đến 2015
pre_df = pre_df[pre_df.year <= 2015]

In [126]:
pre_df

,title,date,stock,year
356.0,Transocean Announces Shell Early Termination o...,2015-12-28 04:19:00-05:00,A,2015
357.0,Benzinga's Top Upgrades,2015-12-09 09:56:00-05:00,A,2015
358.0,Baird Upgrades Agilent Technologies to Outperf...,2015-12-09 06:52:00-05:00,A,2015
359.0,"Goldman Upgrades Agilent Technologies, FEI Com...",2015-12-08 10:19:00-05:00,A,2015
360.0,Goldman Sachs Upgrades Agilent Technologies to...,2015-12-08 05:36:00-05:00,A,2015
...,...,...,...,...
1413824.0,5 Consumer Goods Stocks With The Lowest PEG Ratio,2014-09-02 09:30:00-04:00,ZX,2014
1413825.0,China Zenix Auto International Limited Reports...,2014-08-21 07:23:00-04:00,ZX,2014
1413826.0,China Zenix Auto Reports Q1 EPS of $0.04; Reve...,2014-05-15 05:41:00-04:00,ZX,2014
1413827.0,China Zenix Names Martin Cheung as CFO,2014-03-06 06:19:00-05:00,ZX,2014
1413828.0,China Zenix CFO Yifan Li Resigns for Personal ...,2014-02-24 06:37:00-05:00,ZX,2014

In [127]:
pre_df.groupby('year').count()

       title    date   stock
year
2014  129949  129949  129949
2015  132877  132877  132877

In [128]:
# Lọc các mã có news headline < 25
s = pre_df.stock.value_counts()
pre_df = pre_df[pre_df.stock.isin(s[s >= 25].index)]

In [129]:
#Split Datetime để merge với bảng stock price dự trên date time
pre_df['merged'] = [str(d).split(' ')[0] for d in pre_df['date']]
pre_df

C:\Users\DELL\AppData\Local\Temp\ipykernel_13436\2150071546.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pre_df['merged'] = [str(d).split(' ')[0] for d in pre_df['date']]

,title,date,stock,year,merged
356.0,Transocean Announces Shell Early Termination o...,2015-12-28 04:19:00-05:00,A,2015,2015-12-28
357.0,Benzinga's Top Upgrades,2015-12-09 09:56:00-05:00,A,2015,2015-12-09
358.0,Baird Upgrades Agilent Technologies to Outperf...,2015-12-09 06:52:00-05:00,A,2015,2015-12-09
359.0,"Goldman Upgrades Agilent Technologies, FEI Com...",2015-12-08 10:19:00-05:00,A,2015,2015-12-08
360.0,Goldman Sachs Upgrades Agilent Technologies to...,2015-12-08 05:36:00-05:00,A,2015,2015-12-08
...,...,...,...,...,...
1413375.0,Imperial Capital Maintains Neutral on Zumiez I...,2014-01-09 06:21:00-05:00,ZUMZ,2014,2014-01-09
1413376.0,"Shares of Zumiez Resume, Now Down ~5%",2014-01-08 16:32:00-05:00,ZUMZ,2014,2014-01-08
1413377.0,Shares of Zumiez to Resume Trade at 4:30PM EST,2014-01-08 16:08:00-05:00,ZUMZ,2014,2014-01-08
1413378.0,Zumiez Inc. Lowers Q4 EPS Guidance from $0.60-...,2014-01-08 16:02:00-05:00,ZUMZ,2014,2014-01-08
1413379.0,"Zumiez Dec. Same-Store Sales Down 2.4%, Sales ...",2014-01-08 16:00:00-05:00,ZUMZ,2014,2014-01-08

##### Prepare stock price data in Huge Stock Market Dataset datasets and concat with news headlines data
1. Load data
2. Concat with news headlines dựa trên các tiêu chí cùng stock, datetime

In [130]:
# Load file path and merge 2 bang news headlines va stock price
import os

path = 'Datasets/Stocks/'
arr = []
output = []
stock_names = pre_df.stock.value_counts().index
# print(stock_names)
for file in os.listdir(path) :
    if file.split('.')[0].upper() in stock_names: 
        arr.append([file.split('.')[0],path+file])
        df_stock = pd.read_csv(path+file)
        df_headlines = pre_df[pre_df.stock == file.split('.')[0].upper()]
        merged_df = pd.merge(df_headlines,df_stock, left_on = 'merged',right_on='Date')
        output.append(merged_df)

In [131]:
data = pd.concat(output,axis =0, ignore_index =True)
data

,title,date,stock,year,merged,Date,Open,High,Low,Close,Volume,OpenInt
0,Transocean Announces Shell Early Termination o...,2015-12-28 04:19:00-05:00,A,2015,2015-12-28,2015-12-28,41.172,41.232,40.683,40.939,1488227,0
1,Benzinga's Top Upgrades,2015-12-09 09:56:00-05:00,A,2015,2015-12-09,2015-12-09,40.419,40.959,40.085,40.154,4218193,0
2,Baird Upgrades Agilent Technologies to Outperf...,2015-12-09 06:52:00-05:00,A,2015,2015-12-09,2015-12-09,40.419,40.959,40.085,40.154,4218193,0
3,"Goldman Upgrades Agilent Technologies, FEI Com...",2015-12-08 10:19:00-05:00,A,2015,2015-12-08,2015-12-08,39.791,40.448,39.607,40.340,4420908,0
4,Goldman Sachs Upgrades Agilent Technologies to...,2015-12-08 05:36:00-05:00,A,2015,2015-12-08,2015-12-08,39.791,40.448,39.607,40.340,4420908,0
...,...,...,...,...,...,...,...,...,...,...,...,...
181720,Imperial Capital Maintains Neutral on Zumiez I...,2014-01-09 06:21:00-05:00,ZUMZ,2014,2014-01-09,2014-01-09,23.900,24.920,23.750,24.200,781570,0
181721,"Shares of Zumiez Resume, Now Down ~5%",2014-01-08 16:32:00-05:00,ZUMZ,2014,2014-01-08,2014-01-08,26.500,27.110,25.770,26.180,610438,0
181722,Shares of Zumiez to Resume Trade at 4:30PM EST,2014-01-08 16:08:00-05:00,ZUMZ,2014,2014-01-08,2014-01-08,26.500,27.110,25.770,26.180,610438,0
181723,Zumiez Inc. Lowers Q4 EPS Guidance from $0.60-...,2014-01-08 16:02:00-05:00,ZUMZ,2014,2014-01-08,2014-01-08,26.500,27.110,25.770,26.180,610438,0
181724,"Zumiez Dec. Same-Store Sales Down 2.4%, Sales ...",2014-01-08 16:00:00-05:00,ZUMZ,2014,2014-01-08,2014-01-08,26.500,27.110,25.770,26.180,610438,0

In [132]:
data['Trend'] = data.Close - data.Open
data['Trend'] = np.where(data.Trend>0,1,0)
data

,title,date,stock,year,merged,Date,Open,High,Low,Close,Volume,OpenInt,Trend
0,Transocean Announces Shell Early Termination o...,2015-12-28 04:19:00-05:00,A,2015,2015-12-28,2015-12-28,41.172,41.232,40.683,40.939,1488227,0,0
1,Benzinga's Top Upgrades,2015-12-09 09:56:00-05:00,A,2015,2015-12-09,2015-12-09,40.419,40.959,40.085,40.154,4218193,0,0
2,Baird Upgrades Agilent Technologies to Outperf...,2015-12-09 06:52:00-05:00,A,2015,2015-12-09,2015-12-09,40.419,40.959,40.085,40.154,4218193,0,0
3,"Goldman Upgrades Agilent Technologies, FEI Com...",2015-12-08 10:19:00-05:00,A,2015,2015-12-08,2015-12-08,39.791,40.448,39.607,40.340,4420908,0,1
4,Goldman Sachs Upgrades Agilent Technologies to...,2015-12-08 05:36:00-05:00,A,2015,2015-12-08,2015-12-08,39.791,40.448,39.607,40.340,4420908,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
181720,Imperial Capital Maintains Neutral on Zumiez I...,2014-01-09 06:21:00-05:00,ZUMZ,2014,2014-01-09,2014-01-09,23.900,24.920,23.750,24.200,781570,0,1
181721,"Shares of Zumiez Resume, Now Down ~5%",2014-01-08 16:32:00-05:00,ZUMZ,2014,2014-01-08,2014-01-08,26.500,27.110,25.770,26.180,610438,0,0
181722,Shares of Zumiez to Resume Trade at 4:30PM EST,2014-01-08 16:08:00-05:00,ZUMZ,2014,2014-01-08,2014-01-08,26.500,27.110,25.770,26.180,610438,0,0
181723,Zumiez Inc. Lowers Q4 EPS Guidance from $0.60-...,2014-01-08 16:02:00-05:00,ZUMZ,2014,2014-01-08,2014-01-08,26.500,27.110,25.770,26.180,610438,0,0
181724,"Zumiez Dec. Same-Store Sales Down 2.4%, Sales ...",2014-01-08 16:00:00-05:00,ZUMZ,2014,2014-01-08,2014-01-08,26.500,27.110,25.770,26.180,610438,0,0

In [ ]:
data.title.replace("[^a-zA-Z0-9]"," ",regex=True, inplace=True)

In [133]:
data.to_csv("Data_merged.csv")